version: '2'

networks:
  smartcar:

services:
  ca.sales1.smartcar.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.sales1.smartcar.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.sales1.smartcar.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/98ba786d716c83478ff398ad3c32e2b8e6f3465978ed119c13cfcf6f8eb7825e_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/sales1.smartcar.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.sales1.smartcar.com
    networks:
      - smartcar
  ca.sales2.smartcar.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.sales2.smartcar.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.sales2.smartcar.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/45533bf5d25926327639001d927c5cf87276aea95402c20fe98e38df63279b2e_sk
    ports:
      - "7055:7055"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/sales2.smartcar.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.sales2.smartcar.com
    networks:
      - smartcar
