version: '2'

networks:
  smartcar:

services:
  ca.sales1.smartcar.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.sales1.smartcar.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.sales1.smartcar.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/90df09eada6bafab2e676b3f0ec400828c062a3792fd048d25c9eb40dca9aecf_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/sales1.smartcar.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.sales1.smartcar.com
    networks:
      - smartcar
  ca.sales2.smartcar.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.sales2.smartcar.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.sales2.smartcar.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/102806fa6c60b07719c5bf84699fefa88d8f2efd4e6eabc716911a104d656872_sk
    ports:
      - "7055:7055"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/sales2.smartcar.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.sales2.smartcar.com
    networks:
      - smartcar
